### ISSUE TITLE
Errors raised with normal coupons

### ISSUE THREAD

**Issue by Jon007** [MarieComet/wcs-sell-coupons#12]
Sadly the plugin still impacts normal coupons, in my production case, resulting in impossible for customers to check out until the plugin is disabled :(
more fixes on the way..

**Comment by MarieComet** [comment]
What do you mean by "still impacts **normal** coupons" ?
Coupons created by the plugin are the same post type than coupon manually created.

**Comment by Jon007** [comment]
This filter was failing to return the existing coupon data, so if you add a coupon _which is another type of coupon not a gift coupon_ some of the information is lost.  
            add_filter('woocommerce_add_cart_item_data', array($this, 'wcs_add_cart_item_custom_data'), 10, 2 );
checking in now.

This then caused validation errors on the other coupon which prevented checkout (in the case that is was an auto-add coupon which could not be removed).

**Comment by Jon007** [comment]
When filtering, wcs_add_cart_item_custom_data needs to always return the $cart_item_meta parameter.

Previously the filter only returned the data if it is a gift coupon.

Otherwise as it did not return $cart_item_meta, this means any existing $cart_item_meta not added by this plugin was deleted.

**Comment by MarieComet** [comment]
So, it's ok now with your fix ?

**Comment by Jon007** [comment]
Yes, that is fixed.
It's a common type of error in Wordpress programming and very easy to make.  It's not an obvious programming construct that in the case of no processing required on a filter, the first parameter must be returned.
