### ISSUE TITLE
Form not translated in French in shop

### ISSUE THREAD

**Issue by nautilebleu** [MarieComet/wcs-sell-coupons#22]
Hi,

I'm configuring a shop with wcs-sell-coupons. It has been directly installed from Wordpress admin.

The extension is activated and works except that the form in the shop is not translated in French (while everything else is)

I've try to resync the translations files from the admin with Loco translate. 

The theme is Astra.

Do I miss something for activating the translation of the wcs-sell-coupons extension?

**Comment by MarieComet** [comment]
Hi,
I've [updated the translations files path](https://github.com/MarieComet/wcs-sell-coupons/commit/7376ca92d958391d6acb05e2014173ad6498f78b), can you download and install the plugin again ?

**Comment by nautilebleu** [comment]
Hello

It's good thanks :)
