### ISSUE TITLE
HTML Bug

### ISSUE THREAD

**Issue by CaptainKurtis** [MarieComet/wcs-sell-coupons#23]
Hello, thank you for this great plugin, very useful, light and smartly designed.
I might have found a HTML bug :
I installed the plugin in a very custom set up (custom theme + several custom plugins). On the front-end coupon product page the div with .wcs-data class is closed twice. I had to comment line 195 on woo-sell-coupons.php to correct my layout.
It may be a specific error related to my theme, so I didn't made a pull request, but I thought it may be useful to mention it here. 
Thanks for all !

**Comment by MarieComet** [comment]
Hi,
thanks for that, you're right there is a div closed twice.
Fixed here https://github.com/MarieComet/wcs-sell-coupons/commit/0a962e6682ab2a7d01b092ae0c19405a6e8258fc
